<?php
$arr=[
    '4shared'=>'https://www.4shared.com/web/q/#query=%s&sort=size%2Cdesc',
    'acronimos'=>'https://www.acronymfinder.com/~/search/af.aspx?string=exact&Acronym=%s',
    'alexa'=>'https://alexa.com/siteinfo/%s',
    'antônimos'=>'https://www.antonimos.com.br/busca.php?q=%s',
    'atom'=>'https://atom.io/packages/search?q=%s',
    'books (b-ok)'=>'https://b-ok.lat/s/?q=%s',
    'bing'=>'https://www.bing.com/search?q=%s',
    'buscape'=>'https://www.buscape.com.br/search?page=1&invalidPath=false&sortBy=prod_items_sort_by_price_asc&q=%s&no-shortcut=1',
    'duck'=>'https://duckduckgo.com/?kl=br-pt&q=%s&ia=web',
    'dicio'=>'https://www.dicio.com.br/pesquisa.php?q=%s',
    'discogs'=>'https://www.discogs.com/search/?q=%s&type=all',
    'documentários (dailymotion)'=>'https://duckduckgo.com/?q=%s+site%3Adailymotion.com&kl=br-pt&iar=videos&iax=videos&ia=videos&iaf=videoDuration%3Along',
    'emojipedia'=>'https://emojipedia.org/search/?q=%s',
    'extensões (addons mozilla)'=>'https://addons.mozilla.org/en-US/firefox/search/?q=%s&sort=users&type=extension',
    'globo play'=>'https://globoplay.globo.com/busca/?q=%s',
    'google'=>'https://www.google.com.br/search?q=%s',
    'imagens (getty)'=>'https://www.gettyimages.com.br/search/2/image?phrase=%s',
    'imdb'=>'https://www.imdb.com/find?q=%s&ref_=nv_sr_sm',
    'instagram'=>'https://duckduckgo.com/?q=%s+site%3Ainstagram.com&kl=br-pt&ia=web',
    'magnetdl'=>'https://www.magnetdl.com/search/?q=%s&m=1&x=29&y=15',
    'maps (google)'=>'https://www.google.com.br/maps?hl=pt&q=%s',
    'mercado livre'=>'https://lista.mercadolivre.com.br/%s',
    'mint (linux mint)'=>'https://community.linuxmint.com/software/view/%s',
    'music (youtube)'=>'https://music.youtube.com/search?q=%s',
    'news (google)'=>'https://www.google.com.br/search?tbm=nws&q=%s',
    'ok.ru'=>'https://duckduckgo.com/?q=site%3Ahttps%3A%2F%2Fok.ru%2Fvideo%2F+%s+dublado&kl=br-pt&ia=web',
    'ost (soundtrack)'=>'http://download-soundtracks.com/?s=%s',
    'packagist'=>'https://packagist.org/?query=%s',
    'patentes (google)'=>'https://patents.google.com/?q=%s',
    'php'=>'https://www.php.net/manual-lookup.php?pattern=%s&scope=quickref',
    'reclame aqui'=>'https://www.reclameaqui.com.br/busca/?q=%s',
    'so (stackoverflow)'=>'https://stackoverflow.com/search?q=%s',
    'tpb (the pirate bay)'=>'https://thepiratebay.org/search.php?q=%s&cat=0',
    'translator (bing)'=>'https://www.bing.com/translator/?text=%s&from=auto&to=pt',
    'twitter'=>'https://twitter.com/search?f=tweets&vertical=default&q=%s filter:verified&src=typd&lang=pt&f=live',
    'whosampled'=>'https://www.whosampled.com/search/?q=%s',
    'wikipedia (todas)'=>'https://duckduckgo.com/?kl=br-pt&q=%s+site%3Awikipedia.org&ia=web',
    'videos (bing)'=>'https://www.bing.com/videos/search?&q=%s&qft=+filterui:msite-youtube.com&FORM=VRFLTR',
];
ksort($arr);
return $arr;
